package hh.yarkinsv.gui;

import com.intellij.uiDesigner.core.GridLayoutManager;
import hh.yarkinsv.GameState;

import javax.swing.*;
import java.awt.*;

/**
 * Created by RRP-YarkinSV on 04.02.2016.
 */
public class GameTableFrame extends JFrame {

    private GameState game;
    private JPanel panel;

    public GameTableFrame(GameState game) {
        this.game = game;


        JFrame score1 = new TableScoreFrame(game.getTableScore(0));
        JFrame score2 = new TableScoreFrame(game.getTableScore(0));

        this.add(score1.);
        this.add(score2);

        this.add(this.panel);
        this.pack();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
